<?php
$f=fopen("messages.txt","a");
fwrite($f,$_POST['name'].";;\n");
fwrite($f,$_POST['email'].";;\n");
fwrite($f,$_POST['phone'].";;\n");
fwrite($f,$_POST['topic'].";;\n");
fwrite($f,$_POST['message']."~");
fclose($f);
header("location:".$_POST['location']);
?>
